# Generated by Django 3.2 on 2021-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumer',
            field=models.CharField(max_length=11),
        ),
    ]
