# Generated by Django 3.2.5 on 2021-07-23 00:54

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_phonenumer_person_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(unique=True, upload_to=home.models.getFileName),
        ),
    ]
